org: reflexer
app: geb-pinger-bots
service: geb-pinger-bots

provider:
  name: aws
  runtime: nodejs14.x
  region: 'us-west-2'
  environment: ${self:custom.${opt:stage}}
  vpc:
    subnetIds:
      # A VPC with a subnet needs to be manually configured on the AWS dashboard
      # The subnet needs a NAT gateway with internet access
      - ${param:AWS_VPC_SUBNET_ID_1}
      - ${param:AWS_VPC_SUBNET_ID_2}
    securityGroupIds:
      - ${param:AWS_SECURITY_GROUP}

custom:
  # Redirect to either to conf
  kovan: ${self:custom.prod}
  mainnet: ${self:custom.prod}
  
  custom:
  webpack:
    webpackConfig: './webpack.config.js'
    includeModules: true

  # Fetch env vars from the severless dashboard (depends on the stage which can be either kovan or mainnet)
  prod:
    NETWORK: ${opt:stage}
    ETH_RPC: ${param:ETH_RPC}
    ACCOUNTS_PASSPHRASE: ${param:ACCOUNTS_PASSPHRASE}
    SLACK_HOOK_ERROR_URL: ${param:SLACK_HOOK_ERROR_URL}
    SLACK_HOOK_MULTISIG_URL: ${param:SLACK_HOOK_MULTISIG_URL}
    BLOCKNATIVE_API_KEY: ${param:BLOCKNATIVE_API_KEY, null}

plugins:
  - 'serverless-webpack'

functions:

  updateChainlinkETHMedianizer:
    handler: src/index.updateChainlinkETHMedianizer
    timeout: 240
    events:
      - schedule: 
          enabled: ${file(./config/config.${opt:stage}.json):pingers.chainlinkETHMedianizer.enabled}
          rate: rate(${file(./config/config.${opt:stage}.json):pingers.chainlinkETHMedianizer.schedulerInterval} minutes)

  updateUniswapCoinMedianizer:
    handler: src/index.updateUniswapCoinMedianizer
    timeout: 240
    events:
      - schedule: 
          enabled: ${file(./config/config.${opt:stage}.json):pingers.uniswapCoinMedianizer.enabled}
          rate: rate(${file(./config/config.${opt:stage}.json):pingers.uniswapCoinMedianizer.schedulerInterval} minutes)

  updateETHFsm:
    handler: src/index.updateETHFsm
    timeout: 240
    events:
      - schedule: 
          enabled: ${file(./config/config.${opt:stage}.json):pingers.ethFsm.enabled}
          rate: rate(${file(./config/config.${opt:stage}.json):pingers.ethFsm.schedulerInterval} minutes)

  updateTaxCollector:
    handler: src/index.updateTaxCollector
    timeout: 240
    events:
      - schedule: 
          enabled: ${file(./config/config.${opt:stage}.json):pingers.taxCollector.enabled}
          rate: rate(${file(./config/config.${opt:stage}.json):pingers.taxCollector.schedulerInterval} minutes)

  updateStabilityFeeTreasury:
    handler: src/index.updateStabilityFeeTreasury
    timeout: 240
    events:
      - schedule: 
          enabled: ${file(./config/config.${opt:stage}.json):pingers.stabilityFeeTreasury.enabled}
          rate: rate(${file(./config/config.${opt:stage}.json):pingers.stabilityFeeTreasury.schedulerInterval} minutes)

  pauseExecutor:
    handler: src/index.pauseExecutor
    timeout: 240
    events:
      - schedule: 
          enabled: ${file(./config/config.${opt:stage}.json):pingers.pauseExecutor.enabled}
          rate: rate(${file(./config/config.${opt:stage}.json):pingers.pauseExecutor.schedulerInterval} minutes)

  debtSettler:
    handler: src/index.debtSettler
    timeout: 240
    events:
      - schedule: 
          enabled: ${file(./config/config.${opt:stage}.json):pingers.debtSettler.enabled}
          rate: rate(${file(./config/config.${opt:stage}.json):pingers.debtSettler.schedulerInterval} minutes)

  ceilingSetter:
    handler: src/index.ceilingSetter
    timeout: 240
    events:
      - schedule: 
          enabled: ${file(./config/config.${opt:stage}.json):pingers.ceilingSetter.enabled}
          rate: rate(${file(./config/config.${opt:stage}.json):pingers.ceilingSetter.schedulerInterval} minutes)

  collateralAuctionThrottler:
    handler: src/index.collateralAuctionThrottler
    timeout: 240
    events:
      - schedule: 
          enabled: ${file(./config/config.${opt:stage}.json):pingers.collateralAuctionThrottler.enabled}
          rate: rate(${file(./config/config.${opt:stage}.json):pingers.collateralAuctionThrottler.schedulerInterval} minutes)

  debtFloorAdjuster:
    handler: src/index.debtFloorAdjuster
    timeout: 240
    events:
      - schedule: 
          enabled: ${file(./config/config.${opt:stage}.json):pingers.debtFloorAdjuster.enabled}
          rate: rate(${file(./config/config.${opt:stage}.json):pingers.debtFloorAdjuster.schedulerInterval} minutes)

  autoSurplusAuctionedSetter:
    handler: src/index.autoSurplusAuctionedSetter
    timeout: 240
    events:
      - schedule: 
          enabled: ${file(./config/config.${opt:stage}.json):pingers.autoSurplusAuctionedSetter.enabled}
          rate: rate(${file(./config/config.${opt:stage}.json):pingers.autoSurplusAuctionedSetter.schedulerInterval} minutes)
    
  autoSurplusBufferSetter:
    handler: src/index.autoSurplusBufferSetter
    timeout: 240
    events:
      - schedule: 
          enabled: ${file(./config/config.${opt:stage}.json):pingers.autoSurplusBufferSetter.enabled}
          rate: rate(${file(./config/config.${opt:stage}.json):pingers.autoSurplusBufferSetter.schedulerInterval} minutes)
  
  debtAuctionInitialParameterSetter:
    handler: src/index.debtAuctionInitialParameterSetter
    timeout: 240
    events:
      - schedule: 
          enabled: ${file(./config/config.${opt:stage}.json):pingers.debtAuctionInitialParameterSetter.enabled}
          rate: rate(${file(./config/config.${opt:stage}.json):pingers.debtAuctionInitialParameterSetter.schedulerInterval} minutes)
  
  stakedTokensToKeepSetter:
      handler: src/index.stakedTokensToKeepSetter
      timeout: 240
      events:
        - schedule: 
            enabled: ${file(./config/config.${opt:stage}.json):pingers.stakedTokensToKeepSetter.enabled}
            rate: rate(${file(./config/config.${opt:stage}.json):pingers.stakedTokensToKeepSetter.schedulerInterval} minutes)
  
  stakeRewardRefill:
    handler: src/index.stakeRewardRefill
    timeout: 240
    events:
      - schedule: 
          enabled: ${file(./config/config.${opt:stage}.json):pingers.stakeRewardRefill.enabled}
          rate: rate(${file(./config/config.${opt:stage}.json):pingers.stakeRewardRefill.schedulerInterval} minutes)

  balanceChecker:
    handler: src/index.balanceChecker
    timeout: 240
    events:
      - schedule: 
          enabled: ${file(./config/config.${opt:stage}.json):pingers.balanceChecker.enabled}
          rate: rate(${file(./config/config.${opt:stage}.json):pingers.balanceChecker.schedulerInterval} minutes)

  livenessChecker:
    handler: src/index.livenessChecker
    timeout: 240
    events:
      - schedule: 
          enabled: ${file(./config/config.${opt:stage}.json):pingers.livenessChecker.enabled}
          rate: rate(${file(./config/config.${opt:stage}.json):pingers.livenessChecker.schedulerInterval} minutes)
